# Generated by Django 3.1.7 on 2021-03-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0003_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='time_registered',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time Registered'),
        ),
    ]
