# Generated by Django 3.1.7 on 2021-04-04 11:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0009_event_guest_fk'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='occupied_seats',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Occupied Seats'),
        ),
    ]
