# Generated by Django 3.1.7 on 2021-04-04 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lecture', '0010_event_occupied_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(default='No description', max_length=300, verbose_name='Descrtiption'),
        ),
        migrations.AlterField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Summary'),
        ),
    ]
